### ISSUE TITLE
Does each language have to be in a separate cldf, and all parameters present as metadata?

### ISSUE THREAD

**Issue by Anaphory** [clld/lexibank#1]
From trying to feed a lexibank app with my own data, I get an error

```
ERROR
Traceback (most recent call last):
  File "lexibank/scripts/initializedb.py", line 58, in <module>
    initializedb(create=main, prime_cache=prime_cache)
  File "p:\my documents\database\clld_core\clld\scripts\util.py", line 234, in initializedb
    create(args)
  File "lexibank/scripts/initializedb.py", line 40, in main
    import_cldf(os.path.join(datadir, provider, 'cldf'), provider)
  File "p:\my documents\database\lexibank\lexibank\scripts\util.py", line 126, in import_cldf
    import_dataset(os.path.join(dirpath, fname), provider)
  File "p:\my documents\database\lexibank\lexibank\scripts\util.py", line 69, in import_dataset
    assert language.id == row['Language_ID']
AssertionError
```

if my cldf data file contains values for more than one different language. On the other hand, the metadata file takes its name from the individual word list cldf file name, just appending `-metadata.json`. This leads to odd-looking file names (but I have no reason to complain about that), but more importantly it leads to duplicated metadata. Is that redundancy desired, or am I missing a way to specify metadata on a higher level?

**Comment by xrotwang** [comment]
[CLDF](https://github.com/glottobank/cldf) is still a moving target, so e.g. the variant the lexibank app works with is already somewhat superseded. I started fleshing out the spec a bit more recently, see for example the [WALS example dataset](https://github.com/glottobank/cldf/blob/master/examples/wals/README.md).

Making metadata discoverable by appending `-metadata.json` to the filename of the csv file follows the [W3 Model for tabular data and metadata on the web](https://www.w3.org/TR/tabular-data-model/#default-locations-and-site-wide-location-configuration).

Duplicating metadata is not generally desirable :) It's just an implementation detail of the lexibank importer - and not a high price to pay in this context, because we generally create the cldf files in code, so duplication happens in an automated way.

**Comment by Anaphory** [comment]
Newer, better CLDF specs are a good thing to keep in mind, and the notes in the WALS example are interesting for future reference. (At the moment, I prioritize getting a lexibank-derivative working over tweaking it.)

Some metadata redundancy is to be expected. In retrospect, I could have phrased my question differently as follows.

> Currently, lexibank's importer seems to assume that one contribution gives you one cldf file for one word list in one language.
> I have a contribution giving me word lists for different languages; would you drop the assumption that one contribution gives one cldf file or that one cldf file contains the word list for one language?

The WALS example suggests that the former is the more important assumption.

**Comment by xrotwang** [comment]
In the lexibank import script this assumption is really only necessary for performance reasons:
- We don't want to keep everything in memory during import, thus we have to batch the stuff to import.
- To decrease language lookup times, we group by same language.

In your use case this may not be necessary, so you could create `Language` instances via

``` python
data.add(Language, 'key', id=...)
```

and just lookup the language via

``` python
language = data['Language'][row['Language_ID']]
```

for each individual row.
